### ISSUE TITLE
🤼 Add Complete teams to cloud-ops-writers

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-technology-services-github-teams#16]

**Comment by mitchdawson1982** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-technology-services-github-teams/16?planning-poker) with Zenhub @Gary-H9 @ASTRobinson

**Comment by mitchdawson1982** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-technology-services-github-teams/16?planning-poker) with Zenhub @kyphutruong

**Comment by Gary-H9** [comment]
To be added @tomwells98 @jennycasanova - should we add anyone else?

**Comment by Gary-H9** [comment]
Resolved in [this](https://github.com/ministryofjustice/nvvs-devops/pull/303) PR
