### ISSUE TITLE
👨‍👩‍👦 Get the rest of the team AWS Access etc 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-technology-services-github-teams#8]
Spoke to Tom, showed him the Cost Explorer, would be good to get the whole team access to this 

- [ ] Tariq, 
- [x] Jenny
- [ ] Chinyere 
- [x] Tom

**Comment by bagg3rs** [comment]
We have a group [here](https://github.com/orgs/ministryofjustice/teams/cloud-ops-writers/members) which can be added to Read Only access

**Comment by bagg3rs** [comment]
We will need to add the writers group to https://github.com/ministryofjustice/aws-root-account for read-only access

**Comment by Gary-H9** [comment]
PR merged, Tom confirmed working for him.

**Comment by Gary-H9** [comment]
This will also be working for Chinyere and Tariq as per [this ](https://github.com/orgs/ministryofjustice/teams/cloud-ops-writers/members) team.
